### ISSUE TITLE
SharePoint list QA automap not populating all fields

### ISSUE THREAD

**Issue by markcpreston** [govforms/govforms-labs#4]
**Describe the bug**
SharePoint list QA automap not populating all fields

**To Reproduce**
1. Open Speaker Request Form in QA environment; 
2. Complete form; 
3. Open SharePoint; 
4. List is not properly populated

**Expected behavior**
SharePoint list should contain all the user entered data

**Be compliant with**
Windows	Edge (latest versions)	
 - Google Chrome (latest versions)	
 - Mozilla Firefox (latest versions)	

macOS
- Safari 12 and later	
- Google Chrome (latest versions)	
- Mozilla Firefox (latest versions)

iOS	
- Safari for iOS 12.1 and later	
- Google Chrome (latest versions)

Android
- Google Chrome (latest versions)	
- Samsung Internet (latest versions)

**Comment by nathdolan** [comment]
This can happen if you forget to press Apply after using the Automap function in the Add Item to SharePoint List action settings page, and/or you forget to deploy the updated service to the QA environment before testing.

Moving to resolved.
